### ISSUE TITLE
update to 0.6.x ?

### ISSUE THREAD

**Issue by davephillips** [JerrySievert/Instruments#1]
Hi Jerry,

I recently made the attempt to upgrade your Polivoks modules to the latest Rack master (0.6.x) and eventually got it right, i.e. the plugin loads and runs fine. I'm not on the Repair Team, I just decided to spend a little time to learn what was involved in the update process. However, I noticed that while you've updated your other plugins you've not yet got to the Instruments. Do you plan on updating it yourself or should I do the whole git PR thing ? Just checking to see what's your plan before I go any further. Btw, I enjoy all your plugins, I'm getting good use from the clock dividers, the Polivoks, and your CV sequencer. Thanks for the good stuff !

**Comment by JerrySievert** [comment]
sorry for not responding earlier, for some reason I've not been receiving GitHub emails.

I hadn't updated mostly because I have a couple of issues with the samples during looping, which isn't occurring anywhere outside of rack - I'll try in 0.6 soon, and see if I can figure out what's going on.

I've also been changing how everything is laid out (see synthkit if you're interested), so I probably wouldn't accept a PR for that reason (at least until it is done).

**Comment by JerrySievert** [comment]
oh, I guess I did actually do a push, thought I was still keeping everything local. go figure.

**Comment by davephillips** [comment]
Hi Jerry ! No problem, I'm glad you did the push. Btw, will you be adding the square wave to the Polivoks module any time soon ? I think it would be nice to have. :)

**Comment by JerrySievert** [comment]
the square wave is the one that had the worst issues - it sounded amazing until it looped, which is frustrating.

**Comment by davephillips** [comment]
Ouch. Understood.

**Comment by JerrySievert** [comment]
give it a try - I shaved off an octave, unfortunately, but square is there.

**Comment by davephillips** [comment]
Thanks for the note, Jerry, the new module works fine so far. :)

**Comment by JerrySievert** [comment]
I'm going to go ahead and close this then :)

due to some hostility from rack maintainers, I likely won't be adding this to the plugin manager, and since it was just a personal fun project, there won't be any compilations - I'm just glad it's working for you!

**Comment by phdsg** [comment]
@JerrySievert if our exchange @ https://github.com/VCVRack/community/issues/405 came across as hostile, apology from me. certainly not my intention.

**Comment by JerrySievert** [comment]
no, it wasn't you @phdsg, but I appreciate that you came by.  I know how hard it is to run open source projects, I maintain one that's used by a few million folks that makes me no money, while making amazon, google, and Microsoft plenty of cash - in fact, I've only made money from open source under 2 circumstances: 1) when running r&d centers and using my position to change company culture, putting a few thousand engineers to work writing and maintaining open source software, and 2) when I was directly paid for it because I worked for the open source development lab (now the linux foundation).

in every situation, I have learned that it helps quite a bit to be humble, and to learn from those around me, that being an asshole for the sake of being an asshole is a very stupid thing to do.

I very much appreciate the work that you are doing, but I find it really difficult to contribute to anything when there's someone with that attitude running it - and I think that's likely as nice as I can state that.
